version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mcq_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"       
    environment:
      MONGO_INITDB_DATABASE: mcq_battle
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mcq_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo

volumes:
  mongo_data: